notifications:
  email:
    recipients:
      - clear-code@ml.commit-email.info

dist: trusty

sudo: required

services:
  - docker

matrix:
  include:
    - env: TYPE=centos-6
    - env: TYPE=centos-7
    - os: osx
      env: LUAROCKS_VERSION=2.4.3
      install:
        - sudo
          installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
        - brew update && brew install luajit libxml2
        - curl -O http://luarocks.github.io/luarocks/releases/luarocks-${LUAROCKS_VERSION}.tar.gz
        - tar xf luarocks-${LUAROCKS_VERSION}.tar.gz
        - cd luarocks-${LUAROCKS_VERSION}
        - ./configure --lua-suffix=jit --with-lua-include=/usr/local/include/luajit-2.0
        - make build
        - sudo make install
        - cd ..
        - sudo luarocks install cqueues
            CRYPTO_DIR=$(brew --prefix openssl)
            OPENSSL_DIR=$(brew --prefix openssl)
        - sudo luarocks install luaunit
      script:
        - test/run-test.lua
        - sample/parse-html-cqueues-thread.lua sample/sample.html

install:
  - docker build
      -t clear-code/xmlua-${TYPE}
      -f travis/Dockerfile.${TYPE}
      .

script:
  - docker run
      --interactive
      --tty
      clear-code/xmlua-${TYPE}
